# give me the oneapi spec for an api, that takes 2 lists (ListA and ListB) and a target value and return true or false and a message from the backend

openapi: 3.0.0
info:
  title: Express.js API
  version: 1.0.0
paths:
  /checksum:
    post:
      summary: Take 2 lists containing integers and a target integer values and return true if 2 values combined are equal to the target value and a message
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                listA:
                  type: array
                  items:
                    type: number
                listB:
                  type: array
                  items:
                    type: number
                target:
                  type: number
              required:
                - listA
                - listB
                - target
      responses:
        '200':
          description: Successful response. Found a match
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: boolean
                  message:
                    type: string
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
